#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
echo "Bootstrap installs all dependencies."

echo "Installing features from git@github.com:casper-sdks/terminus-test-resources.git"

if [ -d "../terminus-test-resources/features" ]
then
    echo "terminus-test-resources exists fetching submodules."
    git submodule update --init --recursive
    git submodule update --remote
else
    echo "Cloning terminus-test-resources.git as submodule."
    git submodule add -f git@github.com:casper-sdks/terminus-test-resources.git ../terminus-test-resources
fi

npm install
